import { Poppins } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600'], 
  variable: '--font-poppins',
});

export const metadata = {
  title: 'RESTAURANT',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="antialiased font-poppins">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
