
import './globals.css';
import { Toaster } from '@/components/ui/sonner';





export const metadata = {
  title: 'RESTAURANT',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
